version: '3'

services:
  patreon-downloader:
    build: .
    container_name: patreon-downloader
    volumes:
      - ./data/downloads:/data/downloads
      - ./data/config:/data/config
    environment:
      - CREATOR_URL=https://www.patreon.com/SantiZap  # Replace with your creator
      - MAX_POSTS=20
      - CHECK_INTERVAL=3600
    restart: unless-stopped